pipeline:

  install:
    image: node:9.9.0
    commands:
      - npm install
    secrets: [NPM_TOKEN]
    when:
      event: [push, tag]

  build:
    image: node:9.9.0
    commands:
      - npm run build --prod
    when:
      event: [push, tag]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      status: [failure]
